#!/bin/bash
exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

echo "artifactory-resource:CHECK noop"

version=V0.3
jq -n --arg version "$version" '[
  {
    release: $version
  }
]' >&3